export const actionTypes = {
    SET_TASKS: "SET_TASKS",
    SELECTED_TODO: "SELECTED_TODO",
    REMOVE_SELECTED_TODO: "REMOVE_SELECTED_TODO",
    REMOVE_SELECTED_TODO: "REMOVE_SELECTED_TODO",
    ADD_TASK: "ADD_TASK",
    REMOVE_TASK: "REMOVE_TASK",
    RESET: "RESET",

}